apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app.name: helloworld
  spec:
    type: ClusterIP
    ports:
      - port: 7933
        targetPort: 7933
        protocol: TCP
        name: helloworld-port
    selector:
      app.name: helloworld